import type { CSSProperties } from 'react';

export const styles: Record<string, CSSProperties> = {
  header: {
    background: 'var(--bg-secondary)',
    borderBottom: '1px solid var(--border)',
    padding: '16px 32px',
    position: 'sticky',
    top: 0,
    zIndex: 50,
    backdropFilter: 'blur(12px)',
  },
  headerInner: {
    maxWidth: 1400,
    margin: '0 auto',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: 14,
  },
  logoBox: {
    width: 38,
    height: 38,
    borderRadius: 'var(--radius)',
    background: 'var(--accent)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: '0 0 20px var(--accent-glow)',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: 700,
    letterSpacing: '-0.3px',
    color: 'var(--text-primary)',
    margin: 0,
    lineHeight: 1.3,
  },
  headerSub: {
    fontSize: 12,
    color: 'var(--text-muted)',
    margin: 0,
  },
  headerRight: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
  },
  badge: {
    fontSize: 12,
    fontWeight: 600,
    color: 'var(--accent)',
    background: 'var(--accent-glow)',
    padding: '4px 12px',
    borderRadius: 20,
    border: '1px solid rgba(99, 102, 241, 0.3)',
  },
  main: {
    flex: 1,
    padding: '28px 32px',
    maxWidth: 1400,
    margin: '0 auto',
    width: '100%',
  },
  card: {
    background: 'var(--bg-secondary)',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius-lg)',
    overflow: 'hidden',
  },
  cardHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '16px 20px',
    borderBottom: '1px solid var(--border)',
  },
  cardTitle: {
    fontSize: 14,
    fontWeight: 600,
    color: 'var(--text-primary)',
    margin: 0,
  },
  form: {
    padding: 20,
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
  },
  field: {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
  },
  label: {
    fontSize: 12,
    fontWeight: 600,
    color: 'var(--text-secondary)',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  },
  input: {
    width: '100%',
    padding: '10px 12px',
    background: 'var(--bg-tertiary)',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius)',
    color: 'var(--text-primary)',
    fontSize: 14,
    fontFamily: 'var(--font)',
    outline: 'none',
    transition: 'border-color 0.15s',
  },
  submitBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    padding: '10px 16px',
    background: 'var(--accent)',
    color: '#fff',
    border: 'none',
    borderRadius: 'var(--radius)',
    fontSize: 14,
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.15s',
    marginTop: 4,
  },
  refreshBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '6px 10px',
    background: 'var(--bg-tertiary)',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius)',
    color: 'var(--text-secondary)',
    cursor: 'pointer',
    transition: 'all 0.15s',
  },
  emptyState: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '60px 20px',
  },
  tableWrap: {
    overflowX: 'auto',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
  },
  th: {
    padding: '10px 16px',
    fontSize: 11,
    fontWeight: 600,
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
    color: 'var(--text-muted)',
    textAlign: 'center',
    borderBottom: '1px solid var(--border)',
    background: 'var(--bg-tertiary)',
  },
  tr: {
    transition: 'background 0.1s',
  },
  td: {
    padding: '12px 16px',
    fontSize: 14,
    borderBottom: '1px solid var(--border)',
  },
  iconBubble: {
    width: 30,
    height: 30,
    borderRadius: 'var(--radius)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  typeBadge: {
    display: 'inline-block',
    padding: '3px 10px',
    borderRadius: 20,
    fontSize: 12,
    fontWeight: 600,
    border: '1px solid',
    background: 'transparent',
  },
  tabNav: {
    display: 'flex',
    gap: 4,
    background: 'var(--bg-tertiary)',
    borderRadius: 'var(--radius)',
    padding: 3,
  },
  tabBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    padding: '7px 16px',
    fontSize: 13,
    fontWeight: 500,
    color: 'var(--text-muted)',
    background: 'transparent',
    border: 'none',
    borderRadius: 'var(--radius)',
    cursor: 'pointer',
    transition: 'all 0.15s',
  },
  tabBtnActive: {
    color: 'var(--text-primary)',
    background: 'var(--bg-secondary)',
    boxShadow: '0 1px 3px rgba(0,0,0,0.2)',
  },
  statBadge: {
    fontWeight: 700,
    fontFamily: 'var(--mono)',
    fontSize: 14,
  },
  searchBox: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    background: 'var(--bg-tertiary)',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius)',
    padding: '6px 10px',
  },
  searchInput: {
    background: 'transparent',
    border: 'none',
    color: 'var(--text-primary)',
    fontSize: 13,
    outline: 'none',
    width: 120,
    fontFamily: 'var(--font)',
  },
  toast: {
    position: 'fixed',
    bottom: 24,
    right: 24,
    background: 'var(--bg-secondary)',
    border: '1px solid',
    borderRadius: 'var(--radius)',
    padding: '12px 20px',
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    fontSize: 14,
    fontWeight: 500,
    boxShadow: 'var(--shadow)',
    zIndex: 100,
    animation: 'slideIn 0.2s ease-out',
  },
};

export function statColor(value: number): string {
  if (value > 50) return '#22c55e';
  if (value > 0) return '#eab308';
  return '#ef4444';
}
